#!/usr/bin/perl

# NOTE! This script is designed to be executed within Atlas V only!

# Look for inactive hosts and send ICMP ping packets (do not listen for replies)

use strict;
use warnings;
use Net::Ping;
use Time::HiRes;
use Data::Dumper;
use JSON;


#my $json = JSON->new( allow_nonref => 1 );
my $json = JSON->new();
warn "$0 $$ running\n";
while (1) {

      
  # Fetch list of ip addresses to ping (not disabled AND not active in 2 mins AND not pinged in 2 mins)
  print $session "SELECT id,ip FROM hosts WHERE disabled=false AND (alive IS NULL OR alive < DATE_SUB(NOW(), INTERVAL 2 MINUTE)) AND (checked IS NULL OR checked < DATE_SUB(NOW(), INTERVAL 2 MINUTE))\n";
  my @records = query_result($session);
  
  my $p = Net::Ping->new('icmp');
  $p->hires();
  my @ids = ();
  foreach my $record (@records) {
    warn "$0 $$ ping host id=".$record->{'id'}." ip=".$record->{'ip'}."\n";
    for (1 .. 3) {
      $p->ping($record->{'ip'}, 0.1);
    }
    print $session "UPDATE hosts SET checked=NOW() WHERE id=".int($record->{'id'})."\n";
    query_result($session);
  }
  $p->close();

  sleep 2;

  # If a host did not respond after 10 seconds of pinging, declare it dead
  print $session "UPDATE hosts SET up=0 WHERE disabled=false AND (up=1 OR up IS NULL) AND (alive IS NULL AND checked IS NOT NULL AND (checked-alive > 10 OR alive IS NULL))\n";
  query_result($session);

}


sub query_result {
  my $session = shift;
  my $cols = [];
  my @records = ();
  while (my $line = <$session>) {
    chomp $line;
    last unless $line; # Empty line = end of response
    next if $line =~ /^#/; # Comment/message
    if ($line =~ /^\!/) {
      # Error
      warn "$0 $$ $line\n";
      last;
    }
    #warn "$0 $$ decode line=".$line."\n";
    if ($line =~ /^\@(.+)/) { $cols = $json->decode($1); next; }
    my $row = $json->decode($line);
    my %hash = ();
    @hash{@{$cols}} = @{$row}; 
    push @records, \%hash;
    #warn "$0 $$ hash=".Dumper(\%hash);
  } 
  return @records;
}

